audit:
  kafka:
    group-id: "dm-aw"
    topic-name: "dm-audit"

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest

server:
  port: 8083
  servlet:
    context-path: /aw

system:
  element:
    queue:
      host: localhost
      port: 9092
